<?php


/**
* Implementation of hook_permission().
*/
function modules_weight_permission() {
	return array(
    'access modules weight' => array(
      'title' => t('Access Module Weights'),
      'description' => t('Access the Module Weights admin section.'),
	),
	);
}

/**
* Implementation of hook_menu().
*/
function modules_weight_menu(){
	$items=Array();

	$items['admin/config/system/module_weight']=Array(
		'title' => t('Module Weights'),
		'description' => '',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('modules_weight_form'),
		'access arguments' => array('access modules weight'),
	);

	return $items;
}

/**
* Implementation of hook_theme().
*/
function modules_weight_theme($existing, $type, $theme, $path) {
	return array(
		'modules_weight_form' => array(
			'arguments' => array('form' => NULL),
			'render element' => 'form',
		),
	);
}

function modules_weight_form($form_state){
	$modules=Array();
	foreach(module_list(true) as $module){
		if($module=='standard') continue;
		$res=db_query("SELECT `weight`,`info` FROM {system} WHERE `type`=:type AND `name`=:name LIMIT 1",Array(':type'=>'module',':name'=>$module));

		foreach($res as $obj){
			$w=$obj->weight;
			$infos=unserialize($obj->info);
			$name=$infos['name'];
			$desc=$infos['description'];

			$modules[]=Array(
				'machine_name'=>$module,
				'weight'=>$w,
				'name'=>$name,
				'description'=>$desc,
			);
		}

	}
	$form=Array();
	
	foreach($modules as $module){
		$form['module_'.$module['machine_name']]=Array(
			'#type'=>'textfield',
			'#title'=>$module['name'],
			'#description'=>$module['description'],
			'#default_value'=>$module['weight'],
			'#attributes'=>Array('class'=> Array('my-elements-weight')),
		);
	}

	$form['submit']=Array(
		'#type'=>'submit',
		'#value'=>t('Submit'),
	);
	//$form['#theme'] = 'modules_weight_form';
	$form['#submit'][] = 'modules_weight_form_submit';
	return $form;
}

function theme_modules_weight_form($variables) {
	$form=$variables['form'];
	drupal_add_tabledrag('modules-weight-table', 'order', 'sibling', 'my-elements-weight');
	$header=Array(t('Machine Name'),t('Module'),t('Weight'));
	$rows=Array();
	foreach($form as $key=>&$elem){
		if(strpos($key,"module_")===0){
			$cell1=preg_replace("/^module_/","",$key);
			$cell2=$elem['#title'].'<br />'.$elem['#description'];
			$elem['#title']='';$elem['#description']='';
			$cell3="";
			$cell3=drupal_render($elem);
			
			$row=Array(Array('data'=>$cell1),Array('data'=>$cell2),Array('data'=>$cell3));
			$rows[] = array(
			  'data' => $row,
			  'class' => array('draggable'),
			);
		}
	}

	//var_dump($form);die();
	$output = theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('id' => 'modules-weight-table')));
	$output .= drupal_render_children($form);
	return $output;
}

function modules_weight_form_submit($form,$form_state){
	foreach($form_state['values'] as $key=>$weight){
		if(strpos($key,"module_")===0 && is_numeric($weight)){
			$modulename=preg_replace("/^module_/","",$key);
			if(trim($modulename)=='') continue;
			db_update('system')
			->fields(array('weight' => $weight))
			->condition('name', $modulename, '=')
			->execute();
		}
	}
	drupal_flush_all_caches();
}
